import Head from 'next/head'
import { Footer } from 'src/components/Footer/Footer'
import { Header } from 'src/components/Header/Header'
import { Main } from 'src/components/Main/Main'
import styles from 'src/styles/Home.module.css'

export default function About() {
  return (
    <div className={styles.container}>
      <Head>
        <title>About Page</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
      </Head>
      <Header />
      <Main page="about" />
      <Footer />
    </div>
  )
}
