import Head from 'next/head'
import { useEffect, useState } from 'react'
import { Footer } from 'src/components/Footer/Footer'
import { Header } from 'src/components/Header/Header'
import { Main } from 'src/components/Main/Main'
import styles from 'src/styles/Home.module.css'

export default function Home() {
  const [count, setCount] = useState(1)

  const handleClick = (e) => {
    setCount((prev) => prev + 1)
  }

  useEffect(() => {
    document.body.style.backgroundColor = 'lightblue'

    return () => {
      document.body.style.backgroundColor = ''
    }
  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Index Page</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
      </Head>
      <Header />
      <h2>{count}</h2>
      <button onClick={handleClick}>ボタン</button>
      <Main page="index" />
      <Footer />
    </div>
  )
}
